### ISSUE TITLE
'anchor link' a11y

### ISSUE THREAD

**Issue by bennypowers** [daKmoR/rocket#141]
markdown.css has 

```css
.markdown-body h1:hover .anchor .octicon-link,
.markdown-body h2:hover .anchor .octicon-link,
.markdown-body h3:hover .anchor .octicon-link,
.markdown-body h4:hover .anchor .octicon-link,
.markdown-body h5:hover .anchor .octicon-link,
.markdown-body h6:hover .anchor .octicon-link {
  visibility: visible;
}

```
but the 'link' icon remains invisible for keyboard users.
